# Generated by Django 5.1.4 on 2025-01-17 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('T20', 'Twenty20'), ('ODI', 'One Day'), ('TEST', 'Test Match')], max_length=4)),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=3)),
                ('jersey_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('matches_played', models.IntegerField(default=0)),
                ('runs_scored', models.IntegerField(default=0)),
                ('wickets_taken', models.IntegerField(default=0)),
            ],
        ),
    ]
